# Generated by Django 4.2.4 on 2023-08-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('Home', 'Home'), ('About BBTAA Team', 'About BBTAA Team'), ('Our Services', 'Our Services'), ('Portfolio', 'Portfolio'), ('Contact Us', 'Contact Us')], max_length=100, unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('banner_main_text_part_one', models.CharField(blank=True, max_length=200)),
                ('banner_main_text_part_two', models.CharField(blank=True, max_length=200)),
                ('banner_main_text_anime', models.CharField(blank=True, max_length=100)),
                ('banner_super_text', models.CharField(blank=True, max_length=200)),
                ('banner_sub_text', models.CharField(blank=True, max_length=200)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.URLField(blank=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
