# Generated by Django 4.2.4 on 2023-08-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_bannervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
